package gui;

import model.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.io.File;
import java.util.*;
import util.SaveService;

public class DeltaTriggerGUI {
    private JFrame janela; private final CardLayout telas=new CardLayout(); private final JPanel raiz=new JPanel(telas);
    private Personagem[] grupo; private javax.swing.Timer timerHistoria; private int indiceLetra; private int wave=0, turnoHeroi=0;
    private Inimigo[] inimigos=new Inimigo[0]; private JPanel arenaInimigos, painelGrupo; private JTextArea log; private JLabel waveLabel; private JButton proximaWave;
    private static final Color FUNDO=new Color(2,10,24), PAINEL=new Color(5,18,36), AZUL=new Color(36,126,255), AZULC=new Color(126,200,255), OURO=new Color(226,166,58), TEXTO=new Color(235,242,250), VERDE=new Color(80,220,150);
    private static final Font TITULO=new Font("Serif",Font.BOLD,32), NORMAL=new Font("Serif",Font.PLAIN,17);
    private final String historia="Em um mundo fragmentado por antigas guerras, o equilíbrio entre os reinos está ameaçado.\n\nDizem que, nas profundezas das florestas do norte, algo despertou. Os lobos, antes apenas sombras nas montanhas, agora se organizam, mais fortes e mais inteligentes.\n\nKael e Lyra, dois irmãos unidos pelo mesmo propósito, partem para descobrir a origem dos ataques.\n\nE isso é apenas o começo...";

    public void iniciar(){ janela=new JFrame("Delta Trigger — Aethoria"); janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); janela.setMinimumSize(new Dimension(1100,720)); janela.setSize(1280,800); janela.setLocationRelativeTo(null); raiz.add(criarMenu(),"MENU"); raiz.add(criarHistoria(),"HISTORIA"); raiz.add(criarEscolha(),"ESCOLHA"); janela.setContentPane(raiz); telas.show(raiz,"MENU"); janela.setVisible(true); }
    private JPanel base(){JPanel p=new JPanel(new BorderLayout(14,14));p.setBackground(FUNDO);p.setBorder(new EmptyBorder(18,24,18,24));return p;}
    private JLabel titulo(String s){JLabel l=new JLabel(s,SwingConstants.CENTER);l.setFont(TITULO);l.setForeground(AZULC);return l;}
    private JButton botao(String s){JButton b=new JButton(s);b.setFont(new Font("Serif",Font.BOLD,17));b.setForeground(TEXTO);b.setBackground(PAINEL);b.setFocusPainted(false);b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(OURO,2),new EmptyBorder(9,18,9,18)));return b;}
    private File asset(String n){File f=new File("assets/"+n);if(!f.exists())f=new File("delta_gui/assets/"+n);return f;}
    private ImageIcon imagem(String n,int w,int h){File f=asset(n);if(!f.exists())return null;return new ImageIcon(new ImageIcon(f.getPath()).getImage().getScaledInstance(w,h,Image.SCALE_SMOOTH));}
    private JPanel criarMenu(){JPanel p=base();JPanel c=new JPanel();c.setOpaque(false);c.setLayout(new BoxLayout(c,BoxLayout.Y_AXIS));JLabel logo=new JLabel(imagem("logo.png",420,195));logo.setAlignmentX(.5f);JLabel sub=new JLabel("UMA JORNADA ENTRE O DESTINO E O CAOS");sub.setForeground(OURO);sub.setFont(NORMAL);sub.setAlignmentX(.5f);JButton novo=botao("NOVO JOGO"),sair=botao("SAIR");for(JButton b:new JButton[]{novo,sair}){b.setAlignmentX(.5f);b.setMaximumSize(new Dimension(350,54));}novo.addActionListener(e->iniciarHistoria());sair.addActionListener(e->janela.dispose());c.add(Box.createVerticalGlue());c.add(logo);c.add(sub);c.add(Box.createVerticalStrut(32));c.add(novo);c.add(Box.createVerticalStrut(12));c.add(sair);c.add(Box.createVerticalGlue());p.add(c);return p;}
    private JTextArea textoHistoria; private JButton continuarHistoria;
    private JPanel criarHistoria(){JPanel p=base();p.add(titulo("HISTÓRIA"),BorderLayout.NORTH);textoHistoria=new JTextArea();textoHistoria.setEditable(false);textoHistoria.setLineWrap(true);textoHistoria.setWrapStyleWord(true);textoHistoria.setFont(new Font("Serif",Font.PLAIN,22));textoHistoria.setForeground(TEXTO);textoHistoria.setBackground(PAINEL);textoHistoria.setBorder(new EmptyBorder(55,80,55,80));JScrollPane sp=new JScrollPane(textoHistoria);sp.setBorder(BorderFactory.createLineBorder(OURO,2));p.add(sp);continuarHistoria=botao("CONTINUAR");continuarHistoria.setEnabled(false);continuarHistoria.addActionListener(e->telas.show(raiz,"ESCOLHA"));JButton pular=botao("MOSTRAR TEXTO TODO");pular.addActionListener(e->finalizarHistoria());JPanel s=new JPanel(new FlowLayout(FlowLayout.CENTER,15,0));s.setOpaque(false);s.add(pular);s.add(continuarHistoria);p.add(s,BorderLayout.SOUTH);return p;}
    private void iniciarHistoria(){textoHistoria.setText("");indiceLetra=0;continuarHistoria.setEnabled(false);telas.show(raiz,"HISTORIA");if(timerHistoria!=null)timerHistoria.stop();timerHistoria=new javax.swing.Timer(28,e->{if(indiceLetra<historia.length()){int n=Math.min(2,historia.length()-indiceLetra);textoHistoria.append(historia.substring(indiceLetra,indiceLetra+n));indiceLetra+=n;}else{timerHistoria.stop();continuarHistoria.setEnabled(true);}});timerHistoria.start();}
    private void finalizarHistoria(){if(timerHistoria!=null)timerHistoria.stop();textoHistoria.setText(historia);continuarHistoria.setEnabled(true);}
    private JPanel criarEscolha(){JPanel p=base();p.add(titulo("ESCOLHA SEU PERSONAGEM"),BorderLayout.NORTH);JPanel cards=new JPanel(new GridLayout(1,2,24,0));cards.setOpaque(false);cards.add(cardPersonagem("KAEL","O IRMÃO — Guerreiro / Atacante","Força, disciplina e um coração que nunca desiste.","kael_clean.png",1));cards.add(cardPersonagem("LYRA","A IRMÃ — Suporte / Mágica","Conhecimento, empatia e um poder que inspira esperança.","lyra_clean.png",2));p.add(cards);return p;}
    private JPanel cardPersonagem(String nome,String classe,String desc,String arq,int escolha){JPanel c=new JPanel(new BorderLayout(8,8));c.setBackground(PAINEL);c.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(AZUL,2),new EmptyBorder(14,20,14,20)));JLabel n=new JLabel("<html><center><font size='7'>"+nome+"</font><br>"+classe+"</center></html>",SwingConstants.CENTER);n.setForeground(OURO);c.add(n,BorderLayout.NORTH);JLabel foto=new JLabel(imagem(arq,260,330),SwingConstants.CENTER);c.add(foto);JTextArea d=new JTextArea(desc+"\n\n"+(escolha==1?"HP 120 • Mana 30":"HP 90 • Mana 60"));d.setEditable(false);d.setOpaque(false);d.setForeground(TEXTO);d.setFont(NORMAL);d.setLineWrap(true);d.setWrapStyleWord(true);JButton b=botao("SELECIONAR "+nome);b.addActionListener(e->iniciarJogo(escolha));JPanel sul=new JPanel(new BorderLayout(5,5));sul.setOpaque(false);sul.add(d);sul.add(b,BorderLayout.SOUTH);c.add(sul,BorderLayout.SOUTH);return c;}
    private void iniciarJogo(int lider){grupo=new Personagem[]{new Guerreiro(),new Suporte()}; if(lider==2){Personagem t=grupo[0];grupo[0]=grupo[1];grupo[1]=t;} wave=0;JPanel f=criarFloresta();raiz.add(f,"FLORESTA");telas.show(raiz,"FLORESTA");}
    private JPanel criarFloresta(){JPanel p=base();p.add(titulo("FLORESTA DOS LOBOS — ÁREA NORMAL"),BorderLayout.NORTH);JLabel bg=new JLabel(imagem("forest_bg.png",900,440));bg.setBorder(BorderFactory.createLineBorder(AZUL,2));p.add(bg);JTextArea txt=new JTextArea("> Você entrou na Floresta dos Lobos.\nO som da água ecoa pelas rochas. Há pegadas recentes no caminho.\n\nObjetivo: atravesse as ondas de lobos e encontre Fenrok.");txt.setEditable(false);txt.setForeground(TEXTO);txt.setBackground(PAINEL);txt.setFont(NORMAL);txt.setRows(5);txt.setBorder(new EmptyBorder(10,12,10,12));JButton explorar=botao("EXPLORAR / INICIAR ONDAS"), inv=botao("INVENTÁRIO"), pers=botao("GRUPO");explorar.addActionListener(e->{wave=0;proximaOnda();});inv.addActionListener(e->mostrarInventario());pers.addActionListener(e->mostrarGrupo());JPanel bs=new JPanel(new FlowLayout(FlowLayout.LEFT));bs.setOpaque(false);bs.add(explorar);bs.add(inv);bs.add(pers);JPanel s=new JPanel(new BorderLayout());s.setOpaque(false);s.add(txt);s.add(bs,BorderLayout.SOUTH);p.add(s,BorderLayout.SOUTH);return p;}
    private void proximaOnda(){wave++;if(wave==1)inimigos=new Inimigo[]{LoboFactory.criarLobinho(),LoboFactory.criarLobinho(),LoboFactory.criarLobinho()};else if(wave==2)inimigos=new Inimigo[]{LoboFactory.criarLobinho(),LoboFactory.criarLobinho(),LoboFactory.criarLobinho()};else if(wave==3)inimigos=new Inimigo[]{LoboFactory.criarLobo(),LoboFactory.criarLobo()};else if(wave==4)inimigos=new Inimigo[]{LoboFactory.criarLobo(),LoboFactory.criarLobo(),LoboFactory.criarLobo()};else if(wave==5)inimigos=new Inimigo[]{new Fenrok()};else{mostrarTransicao();return;}turnoHeroi=0;JPanel b=criarBatalha();raiz.add(b,"BATALHA");telas.show(raiz,"BATALHA");}
    private JPanel criarBatalha(){JPanel p=base();waveLabel=titulo(wave<5?"BATALHA — ONDA "+wave+"/4":"BATALHA — FENROK, O LOBO ALFA");p.add(waveLabel,BorderLayout.NORTH);JPanel centro=new JPanel(new BorderLayout(12,12));centro.setOpaque(false);JLabel fundo=new JLabel(imagem(wave==5?"fenrok_bg.png":(wave>=3?"wolf_bg.png":"forest_bg.png"),760,330),SwingConstants.CENTER);fundo.setBorder(BorderFactory.createLineBorder(wave==5?OURO:AZUL,2));centro.add(fundo);arenaInimigos=new JPanel(new GridLayout(1,Math.max(1,inimigos.length),10,0));arenaInimigos.setOpaque(false);centro.add(arenaInimigos,BorderLayout.SOUTH);p.add(centro);painelGrupo=new JPanel(new GridLayout(1,1,4,4));painelGrupo.setOpaque(false);p.add(painelGrupo,BorderLayout.WEST);atualizarCombatentes();log=new JTextArea("A onda começou!\nVez de "+heroiAtual().getNome()+".");log.setEditable(false);log.setLineWrap(true);log.setWrapStyleWord(true);log.setRows(5);log.setFont(NORMAL);log.setForeground(TEXTO);log.setBackground(PAINEL);log.setBorder(new EmptyBorder(9,12,9,12));JButton atacar=botao("ATACAR"),def=botao("DEFENDER"),hab=botao("HABILIDADE"),inv=botao("ITEM"),fugir=botao("FUGIR");atacar.addActionListener(e->acaoAtacar());def.addActionListener(e->acaoDefender());hab.addActionListener(e->acaoHabilidade());inv.addActionListener(e->mostrarItensBatalha());fugir.addActionListener(e->{if(wave<5)telas.show(raiz,"FLORESTA");else log.append("\nFenrok bloqueia sua fuga!");});proximaWave=botao("PRÓXIMA ETAPA");proximaWave.setVisible(false);proximaWave.addActionListener(e->proximaOnda());JPanel bs=new JPanel(new FlowLayout(FlowLayout.LEFT,8,4));bs.setOpaque(false);for(JButton b:new JButton[]{atacar,hab,def,inv,fugir,proximaWave})bs.add(b);JPanel sul=new JPanel(new BorderLayout());sul.setOpaque(false);sul.add(log);sul.add(bs,BorderLayout.SOUTH);p.add(sul,BorderLayout.SOUTH);return p;}
    private Personagem heroiAtual(){for(int i=0;i<grupo.length;i++){Personagem h=grupo[(turnoHeroi+i)%grupo.length];if(h.vivo())return h;}return grupo[0];}
    private void atualizarCombatentes(){painelGrupo.removeAll();Personagem h=heroiAtual();JPanel c=new JPanel(new BorderLayout());c.setBackground(PAINEL);c.setBorder(BorderFactory.createLineBorder(OURO,2));String arq=h.getNome().equals("Kael")?"kael_clean.png":h.getNome().equals("Lyra")?"lyra_clean.png":"lyra_clean.png";c.add(new JLabel(imagem(arq,150,210),SwingConstants.CENTER),BorderLayout.CENTER);JLabel st=new JLabel("<html><center><b>VEZ DE "+h.getNome().toUpperCase()+"</b><br>HP "+h.getVida()+"/"+h.getVidaMaxima()+"<br>Mana "+h.getMana()+"/"+h.getManaMaxima()+"</center></html>",SwingConstants.CENTER);st.setForeground(TEXTO);c.add(st,BorderLayout.SOUTH);painelGrupo.add(c);arenaInimigos.removeAll();for(Inimigo e:inimigos){JPanel ci=new JPanel(new BorderLayout());ci.setBackground(PAINEL);ci.setBorder(BorderFactory.createLineBorder(e instanceof Fenrok?OURO:AZUL,1));String arqi=e instanceof Fenrok?"fenrok.png":e.getNome().equals("Lobinho")?"lobinho.png":"lobo_clean.png";ci.add(new JLabel(imagem(arqi,e instanceof Fenrok?145:105,e instanceof Fenrok?160:125),SwingConstants.CENTER));JLabel sti=new JLabel("<html><center><b>"+e.getNome()+"</b><br>HP "+e.getVida()+"/"+e.getVidaMaxima()+(e.vivo()?"":"<br>DERROTADO")+"</center></html>",SwingConstants.CENTER);sti.setForeground(e.vivo()?TEXTO:Color.GRAY);ci.add(sti,BorderLayout.SOUTH);arenaInimigos.add(ci);}painelGrupo.revalidate();painelGrupo.repaint();arenaInimigos.revalidate();arenaInimigos.repaint();}
    private Inimigo escolherAlvo(){java.util.List<Inimigo> vivos=new ArrayList<>();for(Inimigo e:inimigos)if(e.vivo())vivos.add(e);if(vivos.isEmpty())return null;if(vivos.size()==1)return vivos.get(0);String[] nomes=new String[vivos.size()];for(int i=0;i<vivos.size();i++)nomes[i]=vivos.get(i).getNome()+" — HP "+vivos.get(i).getVida();String s=(String)JOptionPane.showInputDialog(janela,"Escolha o alvo:","Alvo",JOptionPane.PLAIN_MESSAGE,null,nomes,nomes[0]);if(s==null)return null;for(int i=0;i<nomes.length;i++)if(nomes[i].equals(s))return vivos.get(i);return null;}
    private void acaoAtacar(){Personagem h=heroiAtual();Inimigo alvo=escolherAlvo();if(alvo==null)return;int d=alvo.receberDano(h.atacar());log.append("\n"+h.getNome()+" atacou "+alvo.getNome()+" e causou "+d+" de dano.");fimAcao();}
    private void acaoDefender(){Personagem h=heroiAtual();h.defender();log.append("\n"+h.getNome()+" está defendendo.");fimAcao();}
    private void acaoHabilidade(){Personagem h=heroiAtual();Inimigo alvo=escolherAlvo();if(alvo==null)return;if(h.getMana()<8){log.append("\nMana insuficiente.");return;}h.usarMana(8);if(h.getNome().equals("Lyra")){Personagem alvoCura=grupo[0].getVida()<grupo[1].getVida()?grupo[0]:grupo[1];int antes=alvoCura.getVida();alvoCura.curar(22+h.getInteligencia());log.append("\nLyra usa Luz Restauradora: "+alvoCura.getNome()+" recupera "+(alvoCura.getVida()-antes)+" HP.");}else{int d=alvo.receberDano(h.atacar()+8);log.append("\nKael usa Golpe Delta em "+alvo.getNome()+" e causa "+d+" de dano.");}fimAcao();}
    private void fimAcao(){atualizarCombatentes();if(!haInimigoVivo()){vitoriaOnda();return;}ataqueInimigo();turnoHeroi=(turnoHeroi+1)%grupo.length;atualizarCombatentes();if(!haHeroiVivo()){log.append("\n\nDERROTA. O grupo caiu em batalha.");proximaWave.setText("VOLTAR À FLORESTA");proximaWave.setVisible(true);for(Personagem h:grupo)h.recuperarTudo();proximaWave.addActionListener(e->telas.show(raiz,"FLORESTA"));}else log.append("\nVez de "+heroiAtual().getNome()+".");}
    private void ataqueInimigo(){java.util.List<Personagem> vivos=new ArrayList<>();for(Personagem h:grupo)if(h.vivo())vivos.add(h);if(vivos.isEmpty())return;Random r=new Random();for(Inimigo e:inimigos)if(e.vivo()){Personagem alvo=vivos.get(r.nextInt(vivos.size()));int d=alvo.receberDano(e.atacar());log.append("\n"+e.getNome()+" ataca "+alvo.getNome()+" e causa "+d+" de dano.");if(!alvo.vivo()){log.append(" "+alvo.getNome()+" caiu!");vivos.remove(alvo);if(vivos.isEmpty())break;}}}
    private boolean haInimigoVivo(){for(Inimigo e:inimigos)if(e.vivo())return true;return false;} private boolean haHeroiVivo(){for(Personagem h:grupo)if(h.vivo())return true;return false;}
    private void vitoriaOnda(){int ouro=0;for(Inimigo e:inimigos){ouro+=e.getRecompensa();for(Item it:e.sortearDrops())grupo[0].getInventario().adicionarItem(it);Item m=e.sortearMaterial();if(m!=null)grupo[0].getInventario().adicionarItem(m);}grupo[0].adicionarDinheiro(ouro);log.append("\n\nVITÓRIA! Recompensa: $"+ouro+" e possíveis itens/materiais adicionados ao inventário.");if(wave==5){log.append("\nFenrok foi derrotado. O caminho para Eldoria foi aberto!");proximaWave.setText("CONTINUAR PARA ELDORIA");}else proximaWave.setText("PRÓXIMA ONDA");proximaWave.setVisible(true);atualizarCombatentes();}
    private void mostrarItensBatalha(){
        Personagem dono=grupo[0]; java.util.List<Item> disponiveis=new ArrayList<Item>();
        for(Item it:dono.getInventario().getItens()) if(it.utilizavelEmBatalha() && it.getQuantidade()>0) disponiveis.add(it);
        if(disponiveis.isEmpty()){JOptionPane.showMessageDialog(janela,"Nenhum consumível utilizável em batalha.","Itens",JOptionPane.INFORMATION_MESSAGE);return;}
        String[] op=new String[disponiveis.size()]; for(int i=0;i<op.length;i++){Item it=disponiveis.get(i);op[i]=it.getNome()+" x"+it.getQuantidade()+" — "+(it.getCuraHp()>0?"HP +"+it.getCuraHp():"Mana +"+it.getCuraMana());}
        String escolha=(String)JOptionPane.showInputDialog(janela,"Escolha um consumível:","ITEM — BATALHA",JOptionPane.PLAIN_MESSAGE,null,op,op[0]); if(escolha==null)return;
        Item it=disponiveis.get(Arrays.asList(op).indexOf(escolha)); Personagem alvo=escolherHeroiGUI("Usar "+it.getNome()+" em quem?"); if(alvo==null)return;
        if(!alvo.vivo()){JOptionPane.showMessageDialog(janela,"Esse personagem está derrotado.");return;}
        boolean util=(it.getCuraHp()>0 && alvo.getVida()<alvo.getVidaMaxima()) || (it.getCuraMana()>0 && alvo.getMana()<alvo.getManaMaxima());
        if(!util){JOptionPane.showMessageDialog(janela,"O item não teria efeito agora e não foi consumido.");return;}
        int hp0=alvo.getVida(), mp0=alvo.getMana(); alvo.curar(it.getCuraHp()); alvo.curarMana(it.getCuraMana()); dono.getInventario().removerUmaUnidade(it);
        log.append("\n"+heroiAtual().getNome()+" usou "+it.getNome()+" em "+alvo.getNome()+" (HP +"+(alvo.getVida()-hp0)+", Mana +"+(alvo.getMana()-mp0)+")."); fimAcao();
    }
    private void mostrarTransicao(){JPanel p=base();p.add(titulo("TRANSIÇÃO — CAMINHO PARA ELDORIA"),BorderLayout.NORTH);JLabel bg=new JLabel(imagem("forest_bg.png",900,430));p.add(bg);JTextArea t=new JTextArea("Com Fenrok derrotado, a floresta finalmente silencia.\n\nAo longe surgem as muralhas iluminadas de Eldoria. É hora de descansar, negociar e buscar informações sobre a energia estranha.");t.setEditable(false);t.setForeground(TEXTO);t.setBackground(PAINEL);t.setFont(new Font("Serif",Font.PLAIN,21));t.setBorder(new EmptyBorder(16,20,16,20));JButton seguir=botao("ENTRAR EM ELDORIA");seguir.addActionListener(e->mostrarEldoria());JPanel sul=new JPanel(new BorderLayout());sul.setOpaque(false);sul.add(t);sul.add(seguir,BorderLayout.EAST);p.add(sul,BorderLayout.SOUTH);raiz.add(p,"TRANSICAO");telas.show(raiz,"TRANSICAO");}
    private void mostrarEldoria(){JPanel p=base();p.add(titulo("ELDORIA — CIDADE DOS VIAJANTES"),BorderLayout.NORTH);JPanel centro=new JPanel(new GridLayout(2,2,18,18));centro.setOpaque(false);String[][] locais={{"POUSADA","Descansar e salvar o progresso."},{"LOJA","Comprar, vender e equipar itens."},{"TAVERNA","Conversar com viajantes e procurar pistas."},{"GRUPO / INVENTÁRIO","Consultar os heróis e seus equipamentos."}};for(String[] l:locais){JButton b=botao("<html><center><font size='6'>"+l[0]+"</font><br><font size='4'>"+l[1]+"</font></center></html>");if(l[0].equals("POUSADA"))b.addActionListener(e->pousadaGUI());else if(l[0].equals("LOJA"))b.addActionListener(e->lojaGUI());else if(l[0].equals("TAVERNA"))b.addActionListener(e->tavernaGUI());else b.addActionListener(e->painelGrupoInventario());centro.add(b);}p.add(centro);JLabel rodape=new JLabel("  Ouro do líder: $"+grupo[0].getDinheiro()+"   •   Próximo destino: Caverna dos Slimes",SwingConstants.CENTER);rodape.setForeground(OURO);rodape.setFont(NORMAL);p.add(rodape,BorderLayout.SOUTH);raiz.add(p,"ELDORIA");telas.show(raiz,"ELDORIA");}
    private void pousadaGUI(){Object[] op={"Descansar","Salvar jogo","Voltar"};int r=JOptionPane.showOptionDialog(janela,"A lareira está acesa e os quartos estão prontos.\nO que deseja fazer?","Pousada de Eldoria",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,op,op[0]);if(r==0){for(Personagem h:grupo)if(h.vivo())h.recuperarTudo();JOptionPane.showMessageDialog(janela,"O grupo descansou. HP e Mana foram restaurados.");}else if(r==1){boolean ok=SaveService.salvar(grupo,grupo[0].getNome(),"ELDORIA",5,grupo.length>=3);JOptionPane.showMessageDialog(janela,ok?"Jogo salvo com sucesso!":"Não foi possível salvar o jogo.");}}
    private Personagem escolherHeroiGUI(String titulo){String[] nomes=new String[grupo.length];for(int i=0;i<grupo.length;i++)nomes[i]=grupo[i].getNome();String s=(String)JOptionPane.showInputDialog(janela,"Escolha o personagem:",titulo,JOptionPane.PLAIN_MESSAGE,null,nomes,nomes[0]);if(s==null)return null;for(Personagem h:grupo)if(h.getNome().equals(s))return h;return null;}
    private void lojaGUI(){String[] op={"Comprar","Vender item","Equipar","Voltar"};int r=JOptionPane.showOptionDialog(janela,"Bem-vindo à Loja da Lua Azul.","Loja de Eldoria",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,op,op[0]);if(r==0)comprarGUI();else if(r==1)venderGUI();else if(r==2)equiparGUI();}
    private void comprarGUI(){Personagem h=escolherHeroiGUI("Comprar para quem?");if(h==null)return;String[] nomes={"Espada de Ferro — $35","Armadura de Couro — $30","Cajado Simples — $35","Poção de Vida — $15","Poção de Mana — $18"};String s=(String)JOptionPane.showInputDialog(janela,"Dinheiro de "+h.getNome()+": $"+h.getDinheiro(),"Comprar",JOptionPane.PLAIN_MESSAGE,null,nomes,nomes[0]);if(s==null)return;int i=Arrays.asList(nomes).indexOf(s);int[] precos={35,30,35,15,18};if(!h.gastarDinheiro(precos[i])){JOptionPane.showMessageDialog(janela,"Dinheiro insuficiente.");return;}if(i==0)h.getInventario().adicionarEquipamento(new Equipamento("Espada de Ferro","Arma",35,2,0,0,0,0,0));else if(i==1)h.getInventario().adicionarEquipamento(new Equipamento("Armadura de Couro","Armadura",30,0,2,0,1,0,0));else if(i==2)h.getInventario().adicionarEquipamento(new Equipamento("Cajado Simples","Arma",35,0,0,2,0,0,0));else if(i==3)h.getInventario().adicionarItem(new Item("Pocao de Vida","Pocao",15,30,0));else h.getInventario().adicionarItem(new Item("Pocao de Mana","Pocao",18,0,20));JOptionPane.showMessageDialog(janela,"Compra realizada: "+s.split(" —")[0]+".");}
    private void venderGUI(){Personagem h=escolherHeroiGUI("Vender item de quem?");if(h==null||h.getInventario().getItens().isEmpty()){JOptionPane.showMessageDialog(janela,"Nenhum item disponível para venda.");return;}java.util.List<Item> its=h.getInventario().getItens();String[] n=new String[its.size()];for(int i=0;i<n.length;i++)n[i]=its.get(i).descricao();String s=(String)JOptionPane.showInputDialog(janela,"Escolha o item:","Vender",JOptionPane.PLAIN_MESSAGE,null,n,n[0]);if(s==null)return;Item it=its.get(Arrays.asList(n).indexOf(s));int valor=Math.max(1,it.getPreco()/2);h.adicionarDinheiro(valor);h.getInventario().removerUmaUnidade(it);JOptionPane.showMessageDialog(janela,it.getNome()+" vendido por $"+valor+".");}
    private void equiparGUI(){Personagem h=escolherHeroiGUI("Equipar em quem?");if(h==null||h.getInventario().getEquipamentos().isEmpty()){JOptionPane.showMessageDialog(janela,"Nenhum equipamento disponível.");return;}java.util.List<Equipamento> es=h.getInventario().getEquipamentos();String[] n=new String[es.size()];for(int i=0;i<n.length;i++)n[i]=es.get(i).descricao();String s=(String)JOptionPane.showInputDialog(janela,"Escolha o equipamento:","Equipar",JOptionPane.PLAIN_MESSAGE,null,n,n[0]);if(s==null)return;Equipamento e=es.get(Arrays.asList(n).indexOf(s));h.equipar(e);JOptionPane.showMessageDialog(janela,e.getNome()+" equipado em "+h.getNome()+".");}
    private void tavernaGUI(){if(grupo.length<3){JTextArea txt=new JTextArea("Kael e Lyra entram na taverna. Entre mercadores e aventureiros, uma elfa observa a movimentação.\n\n— Meu nome é Elyra. Também estou investigando a energia estranha que surgiu na região.\n\nDepois de conversarem, Elyra decide acompanhar os irmãos.\n\nELYRA ENTROU NO GRUPO! — Nv. 2 • Arqueira Arcana");txt.setEditable(false);txt.setLineWrap(true);txt.setWrapStyleWord(true);txt.setFont(NORMAL);txt.setBackground(PAINEL);txt.setForeground(TEXTO);txt.setBorder(new EmptyBorder(20,20,20,20));JOptionPane.showMessageDialog(janela,new JScrollPane(txt),"Taverna — Um novo encontro",JOptionPane.PLAIN_MESSAGE);grupo=new Personagem[]{grupo[0],grupo[1],new Elyra()};}else JOptionPane.showMessageDialog(janela,"Elyra já está no grupo. O taverneiro comenta que ruídos estranhos vêm da Caverna dos Slimes.");int r=JOptionPane.showConfirmDialog(janela,"Seguir para a Caverna dos Slimes?","Próximo destino",JOptionPane.YES_NO_OPTION);if(r==JOptionPane.YES_OPTION)entradaCavernaGUI();}
    private void painelGrupoInventario(){StringBuilder s=new StringBuilder();for(Personagem h:grupo){s.append(h.getNome()).append(" — Nv. ").append(h.getNivel()).append(" | HP ").append(h.getVida()).append('/').append(h.getVidaMaxima()).append(" | Mana ").append(h.getMana()).append('/').append(h.getManaMaxima()).append(" | $").append(h.getDinheiro()).append("\n");s.append("  Arma: ").append(h.getArmaEquipada()==null?"nenhuma":h.getArmaEquipada().getNome()).append(" | Armadura: ").append(h.getArmaduraEquipada()==null?"nenhuma":h.getArmaduraEquipada().getNome()).append("\n\n");}JTextArea a=new JTextArea(s.toString());a.setEditable(false);a.setFont(new Font("Monospaced",Font.PLAIN,14));JOptionPane.showMessageDialog(janela,new JScrollPane(a),"Grupo e Equipamentos",JOptionPane.PLAIN_MESSAGE);}
    private void entradaCavernaGUI(){JPanel p=base();p.add(titulo("CAVERNA 1 — REINO DOS SLIMES"),BorderLayout.NORTH);JTextArea t=new JTextArea("Kael, Lyra e Elyra deixam Eldoria e seguem em direção à caverna.\n\nA entrada está escura. Um ruído viscoso ecoa lá de dentro. Pequenos rastros azuis brilham entre as pedras.\n\nPRÓXIMA ETAPA: exploração da caverna, Slimes, Rei Slime e habilidades gráficas completas para Elyra.");t.setEditable(false);t.setLineWrap(true);t.setWrapStyleWord(true);t.setFont(new Font("Serif",Font.PLAIN,23));t.setForeground(TEXTO);t.setBackground(PAINEL);t.setBorder(new EmptyBorder(50,70,50,70));p.add(t);JButton voltar=botao("VOLTAR PARA ELDORIA");voltar.addActionListener(e->telas.show(raiz,"ELDORIA"));p.add(voltar,BorderLayout.SOUTH);raiz.add(p,"CAVERNA1");telas.show(raiz,"CAVERNA1");}
    private void mostrarGrupo(){StringBuilder s=new StringBuilder();for(Personagem h:grupo)s.append(h.getNome()).append(" — Nv. ").append(h.getNivel()).append(" | HP ").append(h.getVida()).append('/').append(h.getVidaMaxima()).append(" | Mana ").append(h.getMana()).append('/').append(h.getManaMaxima()).append('\n');JOptionPane.showMessageDialog(janela,s.toString(),"Grupo",JOptionPane.INFORMATION_MESSAGE);}
    private void mostrarInventario(){if(grupo==null)return;StringBuilder s=new StringBuilder("Inventário compartilhado do líder:\n\n");if(grupo[0].getInventario().getItens().isEmpty())s.append("Nenhum item ainda.");else for(Item i:grupo[0].getInventario().getItens())s.append("• ").append(i.descricao()).append('\n');JOptionPane.showMessageDialog(janela,s.toString(),"Inventário",JOptionPane.INFORMATION_MESSAGE);}
}
