package gui;

import model.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.io.File;
import java.util.*;

public class DeltaTriggerGUI {
    private JFrame janela; private final CardLayout telas=new CardLayout(); private final JPanel raiz=new JPanel(telas);
    private Personagem[] grupo; private javax.swing.Timer timerHistoria; private int indiceLetra; private int wave=0, turnoHeroi=0;
    private Inimigo[] inimigos=new Inimigo[0]; private JPanel arenaInimigos, painelGrupo; private JTextArea log; private JLabel waveLabel; private JButton proximaWave;
    private static final Color FUNDO=new Color(2,10,24), PAINEL=new Color(5,18,36), AZUL=new Color(36,126,255), AZULC=new Color(126,200,255), OURO=new Color(226,166,58), TEXTO=new Color(235,242,250), VERDE=new Color(80,220,150);
    private static final Font TITULO=new Font("Serif",Font.BOLD,32), NORMAL=new Font("Serif",Font.PLAIN,17);
    private final String historia="Em um mundo fragmentado por antigas guerras, o equilíbrio entre os reinos está ameaçado.\n\nDizem que, nas profundezas das florestas do norte, algo despertou. Os lobos, antes apenas sombras nas montanhas, agora se organizam, mais fortes e mais inteligentes.\n\nKael e Lyra, dois irmãos unidos pelo mesmo propósito, partem para descobrir a origem dos ataques.\n\nE isso é apenas o começo...";

    public void iniciar(){ janela=new JFrame("Delta Trigger — Aethoria"); janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); janela.setMinimumSize(new Dimension(1100,720)); janela.setSize(1280,800); janela.setLocationRelativeTo(null); raiz.add(criarMenu(),"MENU"); raiz.add(criarHistoria(),"HISTORIA"); raiz.add(criarEscolha(),"ESCOLHA"); janela.setContentPane(raiz); telas.show(raiz,"MENU"); janela.setVisible(true); }
    private JPanel base(){JPanel p=new JPanel(new BorderLayout(14,14));p.setBackground(FUNDO);p.setBorder(new EmptyBorder(18,24,18,24));return p;}
    private JLabel titulo(String s){JLabel l=new JLabel(s,SwingConstants.CENTER);l.setFont(TITULO);l.setForeground(AZULC);return l;}
    private JButton botao(String s){JButton b=new JButton(s);b.setFont(new Font("Serif",Font.BOLD,17));b.setForeground(TEXTO);b.setBackground(PAINEL);b.setFocusPainted(false);b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(OURO,2),new EmptyBorder(9,18,9,18)));return b;}
    private File asset(String n){File f=new File("assets/"+n);if(!f.exists())f=new File("delta_gui/assets/"+n);return f;}
    private ImageIcon imagem(String n,int w,int h){File f=asset(n);if(!f.exists())return null;return new ImageIcon(new ImageIcon(f.getPath()).getImage().getScaledInstance(w,h,Image.SCALE_SMOOTH));}
    private JPanel criarMenu(){JPanel p=base();JPanel c=new JPanel();c.setOpaque(false);c.setLayout(new BoxLayout(c,BoxLayout.Y_AXIS));JLabel logo=new JLabel(imagem("logo.png",420,195));logo.setAlignmentX(.5f);JLabel sub=new JLabel("UMA JORNADA ENTRE O DESTINO E O CAOS");sub.setForeground(OURO);sub.setFont(NORMAL);sub.setAlignmentX(.5f);JButton novo=botao("NOVO JOGO"),sair=botao("SAIR");for(JButton b:new JButton[]{novo,sair}){b.setAlignmentX(.5f);b.setMaximumSize(new Dimension(350,54));}novo.addActionListener(e->iniciarHistoria());sair.addActionListener(e->janela.dispose());c.add(Box.createVerticalGlue());c.add(logo);c.add(sub);c.add(Box.createVerticalStrut(32));c.add(novo);c.add(Box.createVerticalStrut(12));c.add(sair);c.add(Box.createVerticalGlue());p.add(c);return p;}
    private JTextArea textoHistoria; private JButton continuarHistoria;
    private JPanel criarHistoria(){JPanel p=base();p.add(titulo("HISTÓRIA"),BorderLayout.NORTH);textoHistoria=new JTextArea();textoHistoria.setEditable(false);textoHistoria.setLineWrap(true);textoHistoria.setWrapStyleWord(true);textoHistoria.setFont(new Font("Serif",Font.PLAIN,22));textoHistoria.setForeground(TEXTO);textoHistoria.setBackground(PAINEL);textoHistoria.setBorder(new EmptyBorder(55,80,55,80));JScrollPane sp=new JScrollPane(textoHistoria);sp.setBorder(BorderFactory.createLineBorder(OURO,2));p.add(sp);continuarHistoria=botao("CONTINUAR");continuarHistoria.setEnabled(false);continuarHistoria.addActionListener(e->telas.show(raiz,"ESCOLHA"));JButton pular=botao("MOSTRAR TEXTO TODO");pular.addActionListener(e->finalizarHistoria());JPanel s=new JPanel(new FlowLayout(FlowLayout.CENTER,15,0));s.setOpaque(false);s.add(pular);s.add(continuarHistoria);p.add(s,BorderLayout.SOUTH);return p;}
    private void iniciarHistoria(){textoHistoria.setText("");indiceLetra=0;continuarHistoria.setEnabled(false);telas.show(raiz,"HISTORIA");if(timerHistoria!=null)timerHistoria.stop();timerHistoria=new javax.swing.Timer(28,e->{if(indiceLetra<historia.length()){int n=Math.min(2,historia.length()-indiceLetra);textoHistoria.append(historia.substring(indiceLetra,indiceLetra+n));indiceLetra+=n;}else{timerHistoria.stop();continuarHistoria.setEnabled(true);}});timerHistoria.start();}
    private void finalizarHistoria(){if(timerHistoria!=null)timerHistoria.stop();textoHistoria.setText(historia);continuarHistoria.setEnabled(true);}
    private JPanel criarEscolha(){JPanel p=base();p.add(titulo("ESCOLHA SEU PERSONAGEM"),BorderLayout.NORTH);JPanel cards=new JPanel(new GridLayout(1,2,24,0));cards.setOpaque(false);cards.add(cardPersonagem("KAEL","O IRMÃO — Guerreiro / Atacante","Força, disciplina e um coração que nunca desiste.","kael_clean.png",1));cards.add(cardPersonagem("LYRA","A IRMÃ — Suporte / Mágica","Conhecimento, empatia e um poder que inspira esperança.","lyra_clean.png",2));p.add(cards);return p;}
    private JPanel cardPersonagem(String nome,String classe,String desc,String arq,int escolha){JPanel c=new JPanel(new BorderLayout(8,8));c.setBackground(PAINEL);c.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(AZUL,2),new EmptyBorder(14,20,14,20)));JLabel n=new JLabel("<html><center><font size='7'>"+nome+"</font><br>"+classe+"</center></html>",SwingConstants.CENTER);n.setForeground(OURO);c.add(n,BorderLayout.NORTH);JLabel foto=new JLabel(imagem(arq,260,330),SwingConstants.CENTER);c.add(foto);JTextArea d=new JTextArea(desc+"\n\n"+(escolha==1?"HP 120 • Mana 30":"HP 90 • Mana 60"));d.setEditable(false);d.setOpaque(false);d.setForeground(TEXTO);d.setFont(NORMAL);d.setLineWrap(true);d.setWrapStyleWord(true);JButton b=botao("SELECIONAR "+nome);b.addActionListener(e->iniciarJogo(escolha));JPanel sul=new JPanel(new BorderLayout(5,5));sul.setOpaque(false);sul.add(d);sul.add(b,BorderLayout.SOUTH);c.add(sul,BorderLayout.SOUTH);return c;}
    private void iniciarJogo(int lider){grupo=new Personagem[]{new Guerreiro(),new Suporte()}; if(lider==2){Personagem t=grupo[0];grupo[0]=grupo[1];grupo[1]=t;} wave=0;JPanel f=criarFloresta();raiz.add(f,"FLORESTA");telas.show(raiz,"FLORESTA");}
    private JPanel criarFloresta(){JPanel p=base();p.add(titulo("FLORESTA DOS LOBOS — ÁREA NORMAL"),BorderLayout.NORTH);JLabel bg=new JLabel(imagem("forest_bg.png",900,440));bg.setBorder(BorderFactory.createLineBorder(AZUL,2));p.add(bg);JTextArea txt=new JTextArea("> Você entrou na Floresta dos Lobos.\nO som da água ecoa pelas rochas. Há pegadas recentes no caminho.\n\nObjetivo: atravesse as ondas de lobos e encontre Fenrok.");txt.setEditable(false);txt.setForeground(TEXTO);txt.setBackground(PAINEL);txt.setFont(NORMAL);txt.setRows(5);txt.setBorder(new EmptyBorder(10,12,10,12));JButton explorar=botao("EXPLORAR / INICIAR ONDAS"), inv=botao("INVENTÁRIO"), pers=botao("GRUPO");explorar.addActionListener(e->{wave=0;proximaOnda();});inv.addActionListener(e->mostrarInventario());pers.addActionListener(e->mostrarGrupo());JPanel bs=new JPanel(new FlowLayout(FlowLayout.LEFT));bs.setOpaque(false);bs.add(explorar);bs.add(inv);bs.add(pers);JPanel s=new JPanel(new BorderLayout());s.setOpaque(false);s.add(txt);s.add(bs,BorderLayout.SOUTH);p.add(s,BorderLayout.SOUTH);return p;}
    private void proximaOnda(){wave++;if(wave==1)inimigos=new Inimigo[]{LoboFactory.criarLobinho(),LoboFactory.criarLobinho(),LoboFactory.criarLobinho()};else if(wave==2)inimigos=new Inimigo[]{LoboFactory.criarLobinho(),LoboFactory.criarLobinho(),LoboFactory.criarLobinho()};else if(wave==3)inimigos=new Inimigo[]{LoboFactory.criarLobo(),LoboFactory.criarLobo()};else if(wave==4)inimigos=new Inimigo[]{LoboFactory.criarLobo(),LoboFactory.criarLobo(),LoboFactory.criarLobo()};else if(wave==5)inimigos=new Inimigo[]{new Fenrok()};else{mostrarTransicao();return;}turnoHeroi=0;JPanel b=criarBatalha();raiz.add(b,"BATALHA");telas.show(raiz,"BATALHA");}
    private JPanel criarBatalha(){JPanel p=base();waveLabel=titulo(wave<5?"BATALHA — ONDA "+wave+"/4":"BATALHA — FENROK, O LOBO ALFA");p.add(waveLabel,BorderLayout.NORTH);JPanel centro=new JPanel(new BorderLayout(12,12));centro.setOpaque(false);JLabel fundo=new JLabel(imagem(wave==5?"fenrok_bg.png":"forest_bg.png",760,330),SwingConstants.CENTER);fundo.setBorder(BorderFactory.createLineBorder(wave==5?OURO:AZUL,2));centro.add(fundo);arenaInimigos=new JPanel(new GridLayout(1,Math.max(1,inimigos.length),10,0));arenaInimigos.setOpaque(false);centro.add(arenaInimigos,BorderLayout.SOUTH);p.add(centro);painelGrupo=new JPanel(new GridLayout(2,1,4,4));painelGrupo.setOpaque(false);p.add(painelGrupo,BorderLayout.WEST);atualizarCombatentes();log=new JTextArea("A onda começou!\nVez de "+heroiAtual().getNome()+".");log.setEditable(false);log.setLineWrap(true);log.setWrapStyleWord(true);log.setRows(5);log.setFont(NORMAL);log.setForeground(TEXTO);log.setBackground(PAINEL);log.setBorder(new EmptyBorder(9,12,9,12));JButton atacar=botao("ATACAR"),def=botao("DEFENDER"),hab=botao("HABILIDADE"),inv=botao("ITEM"),fugir=botao("FUGIR");atacar.addActionListener(e->acaoAtacar());def.addActionListener(e->acaoDefender());hab.addActionListener(e->acaoHabilidade());inv.addActionListener(e->mostrarInventario());fugir.addActionListener(e->{if(wave<5)telas.show(raiz,"FLORESTA");else log.append("\nFenrok bloqueia sua fuga!");});proximaWave=botao("PRÓXIMA ETAPA");proximaWave.setVisible(false);proximaWave.addActionListener(e->proximaOnda());JPanel bs=new JPanel(new FlowLayout(FlowLayout.LEFT,8,4));bs.setOpaque(false);for(JButton b:new JButton[]{atacar,hab,def,inv,fugir,proximaWave})bs.add(b);JPanel sul=new JPanel(new BorderLayout());sul.setOpaque(false);sul.add(log);sul.add(bs,BorderLayout.SOUTH);p.add(sul,BorderLayout.SOUTH);return p;}
    private Personagem heroiAtual(){for(int i=0;i<grupo.length;i++){Personagem h=grupo[(turnoHeroi+i)%grupo.length];if(h.vivo())return h;}return grupo[0];}
    private void atualizarCombatentes(){painelGrupo.removeAll();for(Personagem h:grupo){JPanel c=new JPanel(new BorderLayout());c.setBackground(PAINEL);c.setBorder(BorderFactory.createLineBorder(h==heroiAtual()?OURO:AZUL,2));String arq=h.getNome().equals("Kael")?"kael_clean.png":"lyra_clean.png";c.add(new JLabel(imagem(arq,95,120)),BorderLayout.WEST);JLabel st=new JLabel("<html><b>"+h.getNome()+"</b><br>HP "+h.getVida()+"/"+h.getVidaMaxima()+"<br>Mana "+h.getMana()+"/"+h.getManaMaxima()+"</html>");st.setForeground(TEXTO);c.add(st);painelGrupo.add(c);}arenaInimigos.removeAll();for(Inimigo e:inimigos){JPanel c=new JPanel(new BorderLayout());c.setBackground(PAINEL);c.setBorder(BorderFactory.createLineBorder(e instanceof Fenrok?OURO:AZUL,1));String arq=e instanceof Fenrok?"fenrok.png":e.getNome().equals("Lobinho")?"lobinho.png":"lobo_clean.png";c.add(new JLabel(imagem(arq,e instanceof Fenrok?145:105,e instanceof Fenrok?160:125),SwingConstants.CENTER));JLabel st=new JLabel("<html><center><b>"+e.getNome()+"</b><br>HP "+e.getVida()+"/"+e.getVidaMaxima()+(e.vivo()?"":"<br>DERROTADO")+"</center></html>",SwingConstants.CENTER);st.setForeground(e.vivo()?TEXTO:Color.GRAY);c.add(st,BorderLayout.SOUTH);arenaInimigos.add(c);}painelGrupo.revalidate();painelGrupo.repaint();arenaInimigos.revalidate();arenaInimigos.repaint();}
    private Inimigo escolherAlvo(){java.util.List<Inimigo> vivos=new ArrayList<>();for(Inimigo e:inimigos)if(e.vivo())vivos.add(e);if(vivos.isEmpty())return null;if(vivos.size()==1)return vivos.get(0);String[] nomes=new String[vivos.size()];for(int i=0;i<vivos.size();i++)nomes[i]=vivos.get(i).getNome()+" — HP "+vivos.get(i).getVida();String s=(String)JOptionPane.showInputDialog(janela,"Escolha o alvo:","Alvo",JOptionPane.PLAIN_MESSAGE,null,nomes,nomes[0]);if(s==null)return null;for(int i=0;i<nomes.length;i++)if(nomes[i].equals(s))return vivos.get(i);return null;}
    private void acaoAtacar(){Personagem h=heroiAtual();Inimigo alvo=escolherAlvo();if(alvo==null)return;int d=alvo.receberDano(h.atacar());log.append("\n"+h.getNome()+" atacou "+alvo.getNome()+" e causou "+d+" de dano.");fimAcao();}
    private void acaoDefender(){Personagem h=heroiAtual();h.defender();log.append("\n"+h.getNome()+" está defendendo.");fimAcao();}
    private void acaoHabilidade(){Personagem h=heroiAtual();Inimigo alvo=escolherAlvo();if(alvo==null)return;if(h.getMana()<8){log.append("\nMana insuficiente.");return;}h.usarMana(8);if(h.getNome().equals("Lyra")){Personagem alvoCura=grupo[0].getVida()<grupo[1].getVida()?grupo[0]:grupo[1];int antes=alvoCura.getVida();alvoCura.curar(22+h.getInteligencia());log.append("\nLyra usa Luz Restauradora: "+alvoCura.getNome()+" recupera "+(alvoCura.getVida()-antes)+" HP.");}else{int d=alvo.receberDano(h.atacar()+8);log.append("\nKael usa Golpe Delta em "+alvo.getNome()+" e causa "+d+" de dano.");}fimAcao();}
    private void fimAcao(){atualizarCombatentes();if(!haInimigoVivo()){vitoriaOnda();return;}ataqueInimigo();turnoHeroi=(turnoHeroi+1)%grupo.length;atualizarCombatentes();if(!haHeroiVivo()){log.append("\n\nDERROTA. O grupo caiu em batalha.");proximaWave.setText("VOLTAR À FLORESTA");proximaWave.setVisible(true);for(Personagem h:grupo)h.recuperarTudo();proximaWave.addActionListener(e->telas.show(raiz,"FLORESTA"));}else log.append("\nVez de "+heroiAtual().getNome()+".");}
    private void ataqueInimigo(){java.util.List<Personagem> vivos=new ArrayList<>();for(Personagem h:grupo)if(h.vivo())vivos.add(h);if(vivos.isEmpty())return;Random r=new Random();for(Inimigo e:inimigos)if(e.vivo()){Personagem alvo=vivos.get(r.nextInt(vivos.size()));int d=alvo.receberDano(e.atacar());log.append("\n"+e.getNome()+" ataca "+alvo.getNome()+" e causa "+d+" de dano.");if(!alvo.vivo()){log.append(" "+alvo.getNome()+" caiu!");vivos.remove(alvo);if(vivos.isEmpty())break;}}}
    private boolean haInimigoVivo(){for(Inimigo e:inimigos)if(e.vivo())return true;return false;} private boolean haHeroiVivo(){for(Personagem h:grupo)if(h.vivo())return true;return false;}
    private void vitoriaOnda(){int ouro=0;for(Inimigo e:inimigos){ouro+=e.getRecompensa();for(Item it:e.sortearDrops())grupo[0].getInventario().adicionarItem(it);Item m=e.sortearMaterial();if(m!=null)grupo[0].getInventario().adicionarItem(m);}grupo[0].adicionarDinheiro(ouro);log.append("\n\nVITÓRIA! Recompensa: $"+ouro+" e possíveis itens/materiais adicionados ao inventário.");if(wave==5){log.append("\nFenrok foi derrotado. O caminho para Eldoria foi aberto!");proximaWave.setText("CONTINUAR PARA ELDORIA");}else proximaWave.setText("PRÓXIMA ONDA");proximaWave.setVisible(true);atualizarCombatentes();}
    private void mostrarTransicao(){JPanel p=base();p.add(titulo("TRANSIÇÃO — CAMINHO PARA ELDORIA"),BorderLayout.NORTH);JLabel bg=new JLabel(imagem("forest_bg.png",900,480));p.add(bg);JTextArea t=new JTextArea("Com Fenrok derrotado, a floresta finalmente silencia.\n\nKael e Lyra seguem pela trilha até Eldoria. A próxima etapa da GUI será a cidade: taverna, pousada, loja, NPCs e preparação para a Caverna 1.");t.setEditable(false);t.setForeground(TEXTO);t.setBackground(PAINEL);t.setFont(new Font("Serif",Font.PLAIN,21));t.setBorder(new EmptyBorder(16,20,16,20));p.add(t,BorderLayout.SOUTH);raiz.add(p,"TRANSICAO");telas.show(raiz,"TRANSICAO");}
    private void mostrarGrupo(){StringBuilder s=new StringBuilder();for(Personagem h:grupo)s.append(h.getNome()).append(" — Nv. ").append(h.getNivel()).append(" | HP ").append(h.getVida()).append('/').append(h.getVidaMaxima()).append(" | Mana ").append(h.getMana()).append('/').append(h.getManaMaxima()).append('\n');JOptionPane.showMessageDialog(janela,s.toString(),"Grupo",JOptionPane.INFORMATION_MESSAGE);}
    private void mostrarInventario(){if(grupo==null)return;StringBuilder s=new StringBuilder("Inventário compartilhado do líder:\n\n");if(grupo[0].getInventario().getItens().isEmpty())s.append("Nenhum item ainda.");else for(Item i:grupo[0].getInventario().getItens())s.append("• ").append(i.descricao()).append('\n');JOptionPane.showMessageDialog(janela,s.toString(),"Inventário",JOptionPane.INFORMATION_MESSAGE);}
}
