package view;

import model.*;import util.SaveService;

public final class CidadeView {
 private CidadeView(){}
 public static int abrir(Grupo grupo,String cidade,boolean elyraEntrou,int waveFloresta){
  while(true){System.out.println("\n========================================");System.out.println("           "+cidade.toUpperCase()+" — CIDADE DOS VIAJANTES");System.out.println("========================================");System.out.println("Pousada: descansar e salvar o progresso.");System.out.println("Loja: comprar, vender e equipar itens.");System.out.println("Taverna: conversar e procurar pistas.");System.out.println("Grupo/Inventario: consultar herois e equipamentos.");System.out.println(Cores.amarelo("Ouro do grupo: $"+grupo.getOuro()));System.out.println("\n1 - Pousada");System.out.println("2 - Loja");System.out.println("3 - Taverna");System.out.println("4 - Grupo / Inventario");System.out.println("5 - Status dos herois");System.out.println("0 - Sair da cidade");int op=Entrada.lerInt("Escolha: ");if(op==0)return 0;if(op==1)pousada(grupo,cidade,waveFloresta,elyraEntrou);else if(op==2)loja(grupo);else if(op==3){if(!elyraEntrou)return 1;System.out.println(Cores.normal("A taverna continua movimentada, mas voce ja encontrou Elyra."));Entrada.enter();}else if(op==4)grupoInventario(grupo);else if(op==5){for(Personagem p:grupo.getPersonagens())p.status();Entrada.enter();}else System.out.println(Cores.aviso("Opcao invalida. Escolha uma opcao do menu."));}
 }
 private static void pousada(Grupo g,String cidade,int waveFloresta,boolean elyraEntrou){while(true){System.out.println("\n=== POUSADA ===");System.out.println("1 - Descansar");System.out.println("2 - Salvar jogo");System.out.println("0 - Voltar");int op=Entrada.lerInt("Escolha: ");if(op==0)return;if(op==1){for(Personagem p:g.getPersonagens())if(p.vivo())p.recuperarTudo();System.out.println(Cores.sucesso("O grupo descansou. HP e Mana foram restaurados."));}else if(op==2){boolean ok=SaveService.salvar(g,cidade.toUpperCase(),waveFloresta,elyraEntrou);System.out.println(ok?Cores.sucesso("Jogo salvo com sucesso! (save.txt criptografado)"):Cores.vermelho("Nao foi possivel salvar o jogo."));}else System.out.println(Cores.aviso("Opcao invalida. Escolha 1, 2 ou 0."));}}
 private static void loja(Grupo g){while(true){System.out.println("\n=== LOJA ===");System.out.println("Ouro do grupo: $"+g.getOuro());System.out.println("1 - Comprar");System.out.println("2 - Vender item");System.out.println("3 - Vender quantidade");System.out.println("4 - Vender tudo deste item");System.out.println("5 - Equipar equipamento");System.out.println("0 - Voltar");int op=Entrada.lerInt("Escolha: ");if(op==0)return;if(op==1)comprar(g);else if(op==2)vender(g,1);else if(op==3)vender(g,2);else if(op==4)vender(g,3);else if(op==5)equipar(g);else System.out.println(Cores.aviso("Opcao invalida. Escolha 1 a 5 ou 0."));}}
 private static void comprar(Grupo g){while(true){System.out.println("\nProdutos:");System.out.println("1 - Espada de Ferro [Arma] $35 | Forca +2");System.out.println("2 - Armadura de Couro [Armadura] $30 | Defesa +2 | Resistencia +1");System.out.println("3 - Cajado Simples [Arma] $35 | Inteligencia +2");System.out.println("4 - Pocao de Vida [Pocao] $15 | +30 HP");System.out.println("5 - Pocao de Mana [Pocao] $18 | +20 Mana");System.out.println("0 - Voltar");int op=Entrada.lerInt("Produto: ");if(op==0)return;if(op==1){comprarEquipamento(g,new Equipamento("Espada de Ferro","Arma","Comum",35,2,0,0,0,0,0));return;}if(op==2){comprarEquipamento(g,new Equipamento("Armadura de Couro","Armadura","Comum",30,0,2,0,1,0,0));return;}if(op==3){comprarEquipamento(g,new Equipamento("Cajado Simples","Arma","Comum",35,0,0,2,0,0,0));return;}if(op==4){comprarItem(g,new Item("Pocao de Vida","Pocao",15,30,0));return;}if(op==5){comprarItem(g,new Item("Pocao de Mana","Pocao",18,0,20));return;}System.out.println(Cores.aviso("Produto invalido."));}}
 private static void comprarEquipamento(Grupo g,Equipamento e){if(!g.gastarOuro(e.getPreco())){System.out.println(Cores.aviso("Dinheiro insuficiente. O grupo possui $"+g.getOuro()+"."));return;}g.getInventario().adicionarEquipamento(e);System.out.println(Cores.sucesso("Comprado: "+e.getNome()+". Guardado no inventario do grupo."));}
 private static void comprarItem(Grupo g,Item i){if(!g.gastarOuro(i.getPreco())){System.out.println(Cores.aviso("Dinheiro insuficiente. O grupo possui $"+g.getOuro()+"."));return;}g.getInventario().adicionarItem(i);System.out.println(Cores.sucesso("Comprado: "+i.getNome()+" x1."));}
 private static void vender(Grupo g,int modo){if(g.getInventario().getItens().isEmpty()){System.out.println(Cores.aviso("Nenhum item para vender."));return;}System.out.println("\nItens do grupo:");for(int i=0;i<g.getInventario().getItens().size();i++)System.out.println((i+1)+" - "+g.getInventario().getItens().get(i).descricao());System.out.println("0 - Voltar");int op=Entrada.lerInt("Item: ");if(op==0)return;if(op<1||op>g.getInventario().getItens().size()){System.out.println(Cores.aviso("Item invalido."));return;}Item item=g.getInventario().getItens().get(op-1);int qtd=1;if(modo==2)qtd=Entrada.lerInteiroPositivo("Quantidade (1 a "+item.getQuantidade()+"): ");else if(modo==3)qtd=item.getQuantidade();if(qtd>item.getQuantidade()){System.out.println(Cores.aviso("Quantidade indisponivel."));return;}int valor=Math.max(1,item.getPreco()/2)*qtd;g.getInventario().removerQuantidade(item,qtd);g.adicionarOuro(valor);System.out.println(Cores.sucesso(item.getNome()+" vendido: x"+qtd+" por $"+valor+"."));}
 private static void equipar(Grupo g){if(g.getInventario().getEquipamentos().isEmpty()){System.out.println(Cores.aviso("Nenhum equipamento no inventario do grupo."));return;}Personagem p=escolherPersonagem(g);if(p==null)return;while(true){System.out.println("\nEquipamentos disponiveis:");for(int i=0;i<g.getInventario().getEquipamentos().size();i++)System.out.println((i+1)+" - "+g.getInventario().getEquipamentos().get(i).descricao());System.out.println("0 - Voltar");int op=Entrada.lerInt("Equipamento: ");if(op==0)return;if(op<1||op>g.getInventario().getEquipamentos().size()){System.out.println(Cores.aviso("Equipamento invalido."));continue;}Equipamento e=g.getInventario().getEquipamentos().get(op-1);p.equipar(e);System.out.println(Cores.sucesso(e.getNome()+" equipado em "+p.getNome()+"."));System.out.println("Os atributos atualizados podem ser vistos em Status dos herois.");return;}}
 private static Personagem escolherPersonagem(Grupo g){System.out.println("\nEscolha o personagem:");for(int i=0;i<g.getPersonagens().size();i++)System.out.println((i+1)+" - "+Cores.nomePersonagem(g.getPersonagens().get(i).getNome()));System.out.println("0 - Voltar");int op=Entrada.lerInt("Escolha: ");if(op==0)return null;if(op<1||op>g.getPersonagens().size()){System.out.println(Cores.aviso("Personagem invalido."));return null;}return g.getPersonagens().get(op-1);}
 private static void grupoInventario(Grupo g){for(Personagem p:g.getPersonagens())System.out.println(Cores.nomePersonagem(p.getNome())+" — Nv."+p.getNivel()+" | HP "+p.getVida()+"/"+p.getVidaMaxima()+" | Mana "+p.getMana()+"/"+p.getManaMaxima());g.getInventario().mostrar();Entrada.enter();}
}
