package util;

import model.*;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.util.*;import javax.crypto.Cipher;import javax.crypto.spec.SecretKeySpec;

public final class SaveService {
 private static final String ARQUIVO="save.txt",CHAVE="DeltaTrigger2026"; private SaveService(){}
 public static boolean existeSave(){return new File(ARQUIVO).exists();}
 public static boolean salvar(Grupo grupo,String local,int waveFloresta,boolean elyraEntrou){try{StringBuilder d=new StringBuilder();d.append("DELTA_V32\n");d.append("STATE|").append(local).append("|").append(waveFloresta).append("|").append(elyraEntrou).append("\n");d.append("GROUP|").append(grupo.getLider()).append("|").append(grupo.getOuro()).append("\n");int i=0;for(Personagem p:grupo.getPersonagens()){d.append("P|").append(i++).append("|").append(p.classe()).append("|").append(p.getNivel()).append("|").append(p.getVidaMaxima()).append("|").append(p.getVida()).append("|").append(p.getManaMaxima()).append("|").append(p.getMana()).append("|").append(p.getPontosAtributo()).append("|").append(p.getExperiencia()).append("|").append(p.getAtributosBase().salvar()).append("\n");d.append("W|").append(p.getNome()).append("|").append(nome(p.getArmaEquipada())).append("\n");d.append("A|").append(p.getNome()).append("|").append(nome(p.getArmaduraEquipada())).append("\n");d.append("B|").append(p.getNome()).append("|").append(nome(p.getBotasEquipadas())).append("\n");d.append("C|").append(p.getNome()).append("|").append(nome(p.getAcessorioEquipado())).append("\n");}for(Item it:grupo.getInventario().getItens())d.append("I|").append(it.getNome()).append("|").append(it.getTipo()).append("|").append(it.getPreco()).append("|").append(it.getCuraHp()).append("|").append(it.getCuraMana()).append("|").append(it.getQuantidade()).append("\n");for(Equipamento e:grupo.getInventario().getEquipamentos())d.append("E|").append(e.getNome()).append("|").append(e.getTipo()).append("|").append(e.getRaridade()).append("|").append(e.getPreco()).append("|").append(e.getForca()).append("|").append(e.getDefesa()).append("|").append(e.getInteligencia()).append("|").append(e.getResistencia()).append("|").append(e.getVelocidade()).append("|").append(e.getSorte()).append("\n");Files.write(Paths.get(ARQUIVO),criptografar(d.toString()).getBytes(StandardCharsets.UTF_8));return true;}catch(Exception e){return false;}}
 private static String nome(Equipamento e){return e==null?"-":e.getNome();}
 public static DadosSave carregar(){try{String enc=new String(Files.readAllBytes(Paths.get(ARQUIVO)),StandardCharsets.UTF_8);String t=descriptografar(enc);String[]ls=t.split("\\n");if(ls.length==0||!"DELTA_V32".equals(ls[0]))throw new Exception();String lider="Kael",local="ELDORIA";int wave=5;boolean elyra=false,grupoLido=false;int ouro=0;List<Personagem>ps=new ArrayList<Personagem>();Map<String,String>arma=new HashMap<String,String>(),armadura=new HashMap<String,String>(),botas=new HashMap<String,String>(),acessorio=new HashMap<String,String>();List<String[]>items=new ArrayList<String[]>(),equips=new ArrayList<String[]>();
  for(String l:ls){String[]p=l.split("\\|",-1);if(p.length==0)continue;if("STATE".equals(p[0])&&p.length>=4){local=p[1];wave=Integer.parseInt(p[2]);elyra=Boolean.parseBoolean(p[3]);}else if("GROUP".equals(p[0])&&p.length>=3){lider=p[1];ouro=Integer.parseInt(p[2]);grupoLido=true;}else if("P".equals(p[0])&&p.length>=11){Personagem q=criar(p[2]);q.definirNivel(Integer.parseInt(p[3]));q.definirVidaMaxima(Integer.parseInt(p[4]));q.definirVida(Integer.parseInt(p[5]));q.definirManaMaxima(Integer.parseInt(p[6]));q.definirMana(Integer.parseInt(p[7]));q.definirPontosAtributo(Integer.parseInt(p[8]));q.definirExperiencia(Integer.parseInt(p[9]));restaurarAtributos(q,p[10]);ps.add(q);}else if("W".equals(p[0]))arma.put(p[1],p[2]);else if("A".equals(p[0]))armadura.put(p[1],p[2]);else if("B".equals(p[0]))botas.put(p[1],p[2]);else if("C".equals(p[0]))acessorio.put(p[1],p[2]);else if("I".equals(p[0]))items.add(p);else if("E".equals(p[0]))equips.add(p);}
  if(!grupoLido||ps.size()<2)throw new Exception();Grupo g=new Grupo(ouro,lider);for(Personagem q:ps)g.adicionar(q);for(String[]p:items)g.getInventario().adicionarItem(new Item(p[1],p[2],Integer.parseInt(p[3]),Integer.parseInt(p[4]),Integer.parseInt(p[5]),Integer.parseInt(p[6])));for(String[]p:equips)g.getInventario().adicionarEquipamento(new Equipamento(p[1],p[2],p[3],Integer.parseInt(p[4]),Integer.parseInt(p[5]),Integer.parseInt(p[6]),Integer.parseInt(p[7]),Integer.parseInt(p[8]),Integer.parseInt(p[9]),Integer.parseInt(p[10])));for(Personagem q:g.getPersonagens()){equiparPorNome(q,arma.get(q.getNome()),g);equiparPorNome(q,armadura.get(q.getNome()),g);equiparPorNome(q,botas.get(q.getNome()),g);equiparPorNome(q,acessorio.get(q.getNome()),g);}g.definirLider(lider);return new DadosSave(g,local,wave,elyra);}catch(Exception e){System.out.println(Cores.aviso("O save esta corrompido ou foi criado por uma versao diferente."));return null;}}
 private static void equiparPorNome(Personagem p,String nome,Grupo g){if(nome==null||"-".equals(nome))return;Equipamento e=g.getInventario().encontrarEquipamento(nome);if(e!=null)p.equipar(e);}
 private static Personagem criar(String c){if("Guerreiro".equals(c))return new Guerreiro();if("Suporte".equals(c))return new Suporte();if("Elyra".equals(c))return new Elyra();throw new IllegalArgumentException();}
 private static void restaurarAtributos(Personagem p,String v){String[]a=v.split(",");if(a.length!=6)throw new IllegalArgumentException();int[]at={p.getAtributosBase().getForca(),p.getAtributosBase().getDefesa(),p.getAtributosBase().getInteligencia(),p.getAtributosBase().getResistencia(),p.getAtributosBase().getVelocidade(),p.getAtributosBase().getSorte()};for(int i=0;i<6;i++){int alvo=Integer.parseInt(a[i]);while(at[i]<alvo){p.getAtributosBase().aumentar(i+1);at[i]++;}}}
 private static String criptografar(String s)throws Exception{Cipher c=Cipher.getInstance("AES/ECB/PKCS5Padding");c.init(Cipher.ENCRYPT_MODE,chave());return Base64.getEncoder().encodeToString(c.doFinal(s.getBytes(StandardCharsets.UTF_8)));}
 private static String descriptografar(String s)throws Exception{Cipher c=Cipher.getInstance("AES/ECB/PKCS5Padding");c.init(Cipher.DECRYPT_MODE,chave());return new String(c.doFinal(Base64.getDecoder().decode(s)),StandardCharsets.UTF_8);}
 private static SecretKeySpec chave()throws Exception{byte[]h=MessageDigest.getInstance("SHA-256").digest(CHAVE.getBytes(StandardCharsets.UTF_8));return new SecretKeySpec(Arrays.copyOf(h,16),"AES");}
 public static class DadosSave{public final Grupo grupo;public final String local;public final int waveFloresta;public final boolean elyraEntrou;public DadosSave(Grupo g,String l,int w,boolean e){grupo=g;local=l;waveFloresta=w;elyraEntrou=e;}}
}
