package controller;

import model.*;import util.*;import view.*;

public class JogoController {
 private Grupo grupo;private String localAtual="INICIO";private int waveFloresta=0;private boolean elyraEntrou=false;private final Caverna florestaDosLobos=CenarioService.florestaDosLobos();
 public void iniciarNovoJogo(){if(!introducao())return;int escolha=MenuView.escolherLider();if(escolha==0)return;grupo=new Grupo(180,escolha==1?"Kael":"Lyra");Personagem kael=new Guerreiro();Personagem lyra=new Suporte();grupo.adicionar(kael);grupo.adicionar(lyra);Equipamento espada=new Equipamento("Espada Inicial","Arma","Comum",0,1,0,0,0,0,0);Equipamento armaduraK=new Equipamento("Armadura Inicial","Armadura","Comum",0,0,2,0,0,0,0);Equipamento cajado=new Equipamento("Cajado Inicial","Arma","Comum",0,0,0,1,0,0,0);Equipamento vestimenta=new Equipamento("Vestimenta Inicial","Armadura","Comum",0,0,1,1,1,0,0);grupo.getInventario().adicionarEquipamento(espada);grupo.getInventario().adicionarEquipamento(armaduraK);grupo.getInventario().adicionarEquipamento(cajado);grupo.getInventario().adicionarEquipamento(vestimenta);kael.equipar(espada);kael.equipar(armaduraK);lyra.equipar(cajado);lyra.equipar(vestimenta);grupo.getInventario().adicionarItem(new Item("Pocao de Vida","Pocao",15,30,0,2));grupo.getInventario().adicionarItem(new Item("Pocao de Mana","Pocao",18,0,20,2));localAtual="FLORESTA";cenaFloresta();iniciarFloresta();}
 public void iniciarCarregado(SaveService.DadosSave save){grupo=save.grupo;localAtual=save.local;waveFloresta=save.waveFloresta;elyraEntrou=save.elyraEntrou;grupo.definirLider(save.grupo.getLider());if("ELDORIA".equals(localAtual))abrirEldoria();else if("FLORESTA".equals(localAtual))iniciarFloresta();else System.out.println(Cores.aviso("Este ponto do save ainda nao possui retorno nesta demo."));}
 private boolean introducao(){MenuView.titulo();String[]ch={"INTRO_1","INTRO_2","INTRO_3","INTRO_4","INTRO_5","INTRO_6","INTRO_7"};for(String c:ch){System.out.println("\n"+TextoService.obter(c,"Aethoria enfrenta uma nova ameaca."));Entrada.enter();}return true;}
 private void cenaFloresta(){System.out.println("\n========================================\n          FLORESTA DOS LOBOS\n========================================");System.out.println("Lider escolhido: "+Cores.nomePersonagem(grupo.getLider()));System.out.println("Kael e Lyra entram na floresta para investigar os acontecimentos.");System.out.println("O caminho parece tranquilo, mas algo se move entre as arvores...");Entrada.enter();}
 private void iniciarFloresta(){for(int wave=waveFloresta+1;wave<=5;wave++){waveFloresta=wave;mostrarWave(wave);Inimigo[]inimigos=criarWave(wave);Batalha.Resultado r=Batalha.iniciar(grupo,inimigos,false);if(r==Batalha.Resultado.DERROTA){gameOver();return;}if(r!=Batalha.Resultado.VITORIA)return;if(wave<5){System.out.println(Cores.normal("A floresta fica em silencio por alguns instantes."));Entrada.enter();}}finalizarFenrok();}
 private Inimigo[] criarWave(int numero){for(Wave wave:florestaDosLobos.getWaves())if(wave.getNumero()==numero){Inimigo[] lista=new Inimigo[wave.getInimigos().size()];for(int i=0;i<lista.length;i++)lista[i]=DadosService.criarInimigo(wave.getInimigos().get(i));return lista;}return new Inimigo[0];}
 private void mostrarWave(int w){System.out.println("\n========================================");if(w<5)System.out.println("          WAVE "+w+"/5");else System.out.println(Cores.inimigo("              CHEFE"));System.out.println("========================================");for(Wave wave:florestaDosLobos.getWaves())if(wave.getNumero()==w){String mensagem=wave.getMensagem();if(w==5)System.out.println(Cores.inimigo(mensagem));else System.out.println(mensagem);break;}Entrada.enter();}
 private void finalizarFenrok(){System.out.println("\n========================================\n"+Cores.sucesso("       FENROK FOI DERROTADO!")+"\n========================================");System.out.println("Fenrok era o protetor da alcateia.");System.out.println("A energia estranha do Delta alterou seu comportamento.");System.out.println("A batalha deixou uma pergunta: o que esta corrompendo a floresta?");System.out.println("\n"+Cores.amarelo("RECOMPENSAS DE FENROK"));Equipamento m=DadosService.criarEquipamento("MANTO_PELAGEM_ALFA"),b=DadosService.criarEquipamento("BOTAS_PELAGEM_ALFA");grupo.getInventario().adicionarEquipamento(m);grupo.getInventario().adicionarEquipamento(b);System.out.println(Cores.sucesso("+ "+m.getNome()+""));System.out.println(Cores.sucesso("+ "+b.getNome()+""));for(Personagem p:grupo.getPersonagens()){int nivelAntes=p.getNivel();int hpAntes=p.getVidaMaxima(),manaAntes=p.getManaMaxima();p.subirNivel();System.out.println(Cores.sucesso(p.getNome()+" subiu para o nivel "+p.getNivel()+"! HP maximo "+hpAntes+" -> "+p.getVidaMaxima()+" | Mana maxima "+manaAntes+" -> "+p.getManaMaxima()));}distribuirPontos();localAtual="ELDORIA";System.out.println(Cores.sucesso("\nO grupo segue para Eldoria."));Entrada.enter();abrirEldoria();}
 private void distribuirPontos(){for(Personagem p:grupo.getPersonagens())while(p.getPontosAtributo()>0){System.out.println("\n=== PONTOS DE ATRIBUTO: "+Cores.nomePersonagem(p.getNome())+" ===");System.out.println("Pontos disponiveis: "+p.getPontosAtributo());System.out.println("1 - Forca\n2 - Defesa\n3 - Inteligencia\n4 - Resistencia\n5 - Velocidade\n6 - Sorte\n0 - Guardar pontos para depois");int op=Entrada.lerInt("Escolha: ");if(op==0)break;if(!p.distribuirPonto(op))System.out.println(Cores.aviso("Opcao invalida."));else System.out.println(Cores.sucesso("Ponto distribuido. Restam "+p.getPontosAtributo()+"."));}}
 private void abrirEldoria(){localAtual="ELDORIA";System.out.println("\n========================================\n               ELDORIA\n========================================");System.out.println("Depois da floresta, as muralhas de Eldoria surgem diante do grupo.");System.out.println("A cidade parece movimentada. Viajantes chegam de varias partes de Aethoria.");Entrada.enter();int r=CidadeView.abrir(grupo,"Eldoria",elyraEntrou,waveFloresta);if(r==1&&!elyraEntrou){encontrarElyra();elyraEntrou=true;entradaCaverna1();}}
 private void encontrarElyra(){System.out.println("\n========================================\n             TAVERNA\n========================================");System.out.println("Um rumor chama a atencao do grupo: criaturas estranhas foram vistas perto da Caverna dos Slimes.");Entrada.enter();System.out.println("Kael e Lyra percebem uma elfa de cabelos vermelhos observando a movimentacao.");System.out.println("Ela se apresenta como Elyra, uma Arqueira Arcana.");System.out.println("Elyra tambem investiga a energia estranha que surgiu na regiao.");Entrada.enter();System.out.println(Cores.elyra("*** ELYRA ENTROU NO GRUPO! ***"));Elyra e=new Elyra();grupo.adicionar(e);grupo.getInventario().adicionarEquipamento(e.getArmaEquipada());grupo.getInventario().adicionarEquipamento(e.getArmaduraEquipada());System.out.println("Nivel: 2 | Classe: Arqueira Arcana");System.out.println("Elyra entra com seus equipamentos iniciais ja equipados.");Entrada.enter();}
 private void entradaCaverna1(){localAtual="CAVERNA1";System.out.println("\n========================================\n          CAVERNA DOS SLIMES\n========================================");System.out.println("O grupo deixa Eldoria e segue em direcao a caverna.");System.out.println("A entrada esta escura. Um ruido estranho vem de dentro.");System.out.println(Cores.amarelo("A Caverna dos Slimes sera desenvolvida usando o mesmo motor de cenario e batalha da V3.2."));Entrada.enter();}
 private void gameOver(){while(true){System.out.println("\n========================================\n"+Cores.vermelho("             GAME OVER")+"\n========================================");System.out.println("Todos os personagens foram derrotados.");System.out.println("\n1 - Carregar jogo salvo\n2 - Voltar ao menu inicial\n3 - Sair");int op=Entrada.lerInt("Escolha: ");if(op==1){if(!SaveService.existeSave()){System.out.println(Cores.aviso("Nenhum jogo salvo foi encontrado."));continue;}SaveService.DadosSave s=SaveService.carregar();if(s!=null){grupo=s.grupo;localAtual=s.local;waveFloresta=s.waveFloresta;elyraEntrou=s.elyraEntrou;if("ELDORIA".equals(localAtual))abrirEldoria();else if("FLORESTA".equals(localAtual))iniciarFloresta();}return;}if(op==2)return;if(op==3){System.out.println(Cores.ciano("Ate a proxima aventura em Aethoria!"));System.exit(0);}System.out.println(Cores.aviso("Opcao invalida. Escolha 1, 2 ou 3."));}}
}
